apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-stations
spec:
  serviceName: "weather-station-service"
  replicas: 2
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
        - name: weather-station
          image: weather_station
          imagePullPolicy: Never
          env:
            - name: STATION_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "weather_topic"
