apiVersion: v1
kind: Pod
metadata:
  name: central-station
spec:
  containers:
    - name: central-station
      image: central-station
#      command: [ "sh", "-c" ]
#      args:
#        - |
#          echo "Starting Java with JFR...";
#          java \
#            -XX:StartFlightRecording=filename=/parquet/jfr/recording.jfr,duration=180s,settings=profile \
#            -jar app.jar;
#          echo "Java process done, sleeping...";
      imagePullPolicy: Never
      env:
        - name: KAFKA_BROKER_HOST
          value: "kafka-service:9092"
        - name: KAFKA_CONSUMER_GROUP_ID
          value: "weather-consumer-group"
        - name: KAFKA_CONSUMER_TOPIC
          value: "weather_topic"
        - name: KAFKA_INVALID_TOPIC
          value: "invalid_weather_topic"
        - name: PARQUET_DIRECTORY
          value: "/parquet"
        - name: BITCASK_DIRECTORY
          value: "/bitcask"
        - name: BITCASK_MAX_BYTES
          value: "4096"
      volumeMounts:
        - name: bitcask-data
          mountPath: /bitcask
        - name: parquet-data
          mountPath: /parquet

  volumes:
    - name: bitcask-data
      hostPath:
        path: /run/desktop/mnt/host/d/Study/Semester 8/Data Intensive/Project/Pipe-Line-Weather-Stations-Monitoring/data/bitcask
        type: DirectoryOrCreate
    - name: parquet-data
      hostPath:
        path: /run/desktop/mnt/host/d/Study/Semester 8/Data Intensive/Project/Pipe-Line-Weather-Stations-Monitoring/data/parquet
        type: DirectoryOrCreate
