apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingester
  template:
    metadata:
      labels:
        app: ingester
    spec:
      containers:
      - name: ingester
        image: ingester:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: incoming-volume
          mountPath: /data/incoming
        - name: processed-volume
          mountPath: /data/processed
      volumes:
      - name: incoming-volume
        hostPath:
          path: D:/Study/data/incoming
          type: DirectoryOrCreate
      - name: processed-volume
        hostPath:
          path: D:/Study/data/processed
          type: DirectoryOrCreate
