apiVersion: v1
kind: Pod
metadata:
  name: ingester
spec:
  containers:
    - name: ingester
      image: ingester
      imagePullPolicy: Never
      env:
        - name: PARQUET_FOLDER
          value: "/parquet"
        - name: ES_INDEX
          value: "weather_data"
        - name: ELASTICSEARCH_HOST
          value: "http://elasticsearch-kibana:9200"
      volumeMounts:
        - name: parquet-data
          mountPath: /parquet

  volumes:
    - name: parquet-data
      hostPath:
        path: /run/desktop/mnt/host/d/Study/Semester 8/Data Intensive/Project/Pipe-Line-Weather-Stations-Monitoring/data/parquet
        type: DirectoryOrCreate
