apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meteo-station
spec:
  serviceName: "meteo-station-service"
  replicas: 1
  selector:
    matchLabels:
      app: meteo-station
  template:
    metadata:
      labels:
        app: meteo-station
    spec:
      containers:
        - name: meteo-station
          image: meteo_station
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "weather_topic"
