apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weather-producer
spec:
  serviceName: "weather-producer-service"
  replicas: 1
  selector:
    matchLabels:
      app: weather-producer
  template:
    metadata:
      labels:
        app: weather-producer
    spec:
      containers:
        - name: weather-producer
          image: weather_producer       
          imagePullPolicy: Never        
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "weather-topic"
