apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-0.kafka-service.default.svc.cluster.local:9092,CONTROLLER://kafka-0.kafka-service.default.svc.cluster.local:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka-service.default.svc.cluster.local:9093"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "ErvdOSvBQo-TNiIYytokWw"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          ports:
            - containerPort: 9092
            - containerPort: 9093
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    /opt/bitnami/kafka/bin/kafka-topics.sh \
                      --create \
                      --topic weather_topic \
                      --bootstrap-server localhost:9092 \
                      --partitions 1 \
                      --replication-factor 1 \

                      /opt/bitnami/kafka/bin/kafka-topics.sh \
                        --create \
                        --topic rain_alerts_topic \
                        --bootstrap-server localhost:9092 \
                        --partitions 1 \
                        --replication-factor 1
                      
                      /opt/bitnami/kafka/bin/kafka-topics.sh \
                        --create \
                        --topic invalid_weather_topic \
                        --bootstrap-server localhost:9092 \
                        --partitions 1 \
                        --replication-factor 1
