version: "3.8"

services:
  elasticsearch:
    image: nshou/elasticsearch-kibana
    ports:
      - "9200:9200"
      - "5601:5601"
    environment:
      - SSL_MODE=false
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - elk-net

  ingester:
    build: ./ingest
    volumes:
      - ./ingest/data/incoming:/data/incoming
      - ./ingest/data/processed:/data/processed
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk-net

networks:
  elk-net:
